// build                                项目构建(webpack)相关代码
// build/build.js                       生产环境构建代码
// build/check-versions.js              检查node、npm等版本
// build/dev-client.js                  热重载
// build/dev-server.js                  构建本地服务器
// build/util.js                        构建工具相关
// build/vue-loader.conf.js             oss加载器配置
// build/webpack.base.conf.js           webpack基础配置
// build/webpack.dev.conf.js            webpack开发环境配置
// build/webpack.prod.conf.js           webpack生产环境配置
// config                               vue基本配置文件（比如监听端口、打包输出等相关配置）
// config/dev.env.js                    开发环境变量
// config/index.js                      项目一些配置变量
// config/prod.env.js                   生产环境变量
// config/test.env.js                   测试环境变量
// node_modules                         用node安装的依赖包
// src                                  资源文件夹，以后我们就在这个目录下写代码
// src/assets                           静态资源（js、oss之类的文件放在此目录下）
// src/components                       公共组件编写的地方
// src/pages                            页面编写的地方（页面使用组件拼出来的，也是vue文件）
// src/router                           路由文件夹 （配置页面跳转）
// src/main.js                          页面程序入口文件，加载各种公共组件
// static                               静态资源（图片之类）json数据之类
// test                                 单元测试、代码测试
// .babelrc                             ES6语法编译配置，用来将es6代码转换为游览器识别的代码
// .editorconfig                        定义代码格式
// .gitignore                           git上传需要忽略的文件格式
// .postcssrc.js                        转换oss工具
// data.json                            测试数据
// goods.json                           测试数据
// index.html                           页面入口
// npm-debug.log                        npm相关log信息
// package.json                         项目基本信息（项目开发所需模板、项目名称、版本）
// readme.txt                           项目说明（如何使用，有哪些方法等等）